selectors=[
"#title",
"body",
"div",
"p",
"div, p, a",
"div p",
"body div",
".note",
"div.example",
"div.example, div.note",
".toc .tocline2",
"ul.toc li.tocline2",
"ul .tocline2",
"tr td.pattern",
"#testDl dt",
"#testDl .vcard",
"#testDl .vcard span",
"div ~ p",
"div > div",
"div ~ div",
"div > p",
"ul.toc > li.tocline2",
"div + p",
"div[class]",
"div[class=example]",
"div[class^=exa]",
"div[class$=mple]",
"div[class*=e]",
"div[class|=dialog]",
"div[class!=made_up]",
"div[class~=example]",
"li:empty",
"div:not(.example)",
"p:nth-child(even)",
"p:nth-child(2n)",
"p:nth-child(odd)",
"p:nth-child(2n+1)",
"p:nth-child(n)",
"p:only-child",
"p:only-of-type",
"p:first-child",
"th:first-of-type",
"p:last-child",
"th:last-of-type",
"td:nth-of-type(even)",
"td:nth-last-of-type(odd)",
"input:checked",
"input:disabled"
]
